targets:
  dev:
    variables:
      catalog_name: "smart_city_dev"
      volume_path: "/Volumes/smart_city_dev/transportation/raw"
      schema_name: "transportation"
      service_principal_id: ""




    
