targets:
  dev:
    variables:
      workspace_host: "https://dbc-2407f8fc-5cf5.cloud.databricks.com"
      catalog_name: "smart_city_dev"
      volume_path: "/Volumes/smart_city_dev/transportation/raw"
      schema_name: "transportation"
      service_principal_id: ""




    
