targets:
  prod:
    variables:
      workspace_host: "https://dbc-2407f8fc-5cf5.cloud.databricks.com"
      catalog_name: "smart_city_prod"
      volume_path: "/Volumes/smart_city_prod/transportation/raw"
      schema_name: "transportation"
      service_principal_id: "3f1f9ec9-591e-40d0-8a28-b7d495b444a2"

